trigger:
- main

pool:
  name: Default

variables:
- name: nala
  value: labrador

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: buildJob
    displayName: 'Build Job'
    steps:
    - script: |
        echo "Nala es una $(nala)"
    - script: |
        echo "##vso[task.setvariable variable=nala]schnautzer"
      name: varChange
- stage: Test
  displayName: 'Test Stage'
  variables:
    pewito: $[stageDependencies.Build.buildJob.outputs['varChange.nala']]
  jobs:
  - job: testJob
    displayName: 'Test Job'
    steps:
    - script: |
        echo "Nala tambien es una $(pewito)"
      condition: eq(variables['pewito'],'schnautzer')