trigger:
  branches:
    include:
      - main

parameters:
- name: environment  
  type: object
  default:
    - dev

variables:
- name: appName
  value: InventoryAPI

stages:
- stage: varAndParStage
  displayName: 'Variable and Parameters stage'
  jobs:
  - job: varAndParJob
    displayName: 'Variable and Parameters job'
    - deployment: varAndParDeploy
      environment: ${{ environment }}
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo 'Deploying InventoryAPI to dev'