trigger:
- main

pool:
  name: Default

variables:
- name: firstValue
  value: valueOne
- name: secondValue
  value: valueTwo

stages: 
- stage: Build
  displayName: 'Showing first variable'
  jobs:
  - job: FirstJob
    displayName: 'First variable job'
    steps:
    - script: |
        echo "This is my first variable $(valueOne)"
      displayName: 'First script'
- stage: Deploy
  displayName: 'Showing second value'
  jobs:
  - job: SecondJob
    displayName: 'Second variable job'
    steps:
    - script: |
        echo "This is my second variable $(valueTwo)"
      displayName: "Second script"