trigger:
- main

variables:
- name: firstVariable
  value: 1
- name: secondVariable
  value: 2

pool:
  name: Default

stages:
- stage: Build
  displayName: 'Stage 1'
  jobs:
  - job: FirstJob
    displayName: 'First Job'
    steps: 
    - script: |
        echo "First variable: $(firstVariable)"
- stage: Test
  displayName: 'Stage 2'
  dependsOn: Build
  jobs:
  - job: scondJob
    displayName: 'Second Job'
    steps:
    - script: |
        echo "Second variable: $(secondVariable)"