trigger:
- main

variables:
  - name: greet
    value: Hello

pool: Default

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - script: |
        echo "${{ variables.greet }} - Build!"
      displayName: 'Waving Build'
    - script: |
        echo "Good bye Build"
      displayName: 'Bye Build'
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  jobs:
  - job: DeployJob
    displayName: 'Deploy Job'
    steps:
    - script: |
        echo "${{ variables.greet }} - This is a deploy job"
        echo "${{ variables.greet }} - This is a deploy job"
  - job: SecondJob
    displayName: 'Second Deploy Job'
    steps:
    - script: |
        echo "Testing a second deploy job"