trigger:
  branches:
    include:
      - main

pool:
  name: kubernetes-cluster

stages:
  - stage: ShowingManifests
    jobs:
      - job: listCopyAndTransfer
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: 'ls -ltr $(Build.SourcesDirectory)/k8s'
        - task: CopyFiles@2
          inputs:
            SourceFolder: $(Build.SourcesDirectory)/k8s
            Contents: '**'
            TargetFolder: $(Build.ArtifactStagingDirectory)
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: $(Build.ArtifactStagingDirectory)
            artifact: manifests
            publishLocation: 'pipeline'

  - stage: DeployDev
    jobs:
      - deployment: DeployInventory
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: current
                    artifactName: manifests
                    targetPath: '$(Pipeline.Workspace)'
                - task: Bash@3
                  inputs:
                    targetType: inline
                    script: |
                      kubectl apply -f $(Pipeline.Workspace)/*.yaml
                      kubectl rollout status deployment/inventory-api
  
  - stage: ValidateDeployment
    jobs:
      - job: ValidateJob
        steps:
        - task: Bash@3
          inputs:
            targetType: inline
            script: |
              kubectl get pods
              kubectl get svc
              kubectl describe deployment inventory-api