parameters:
  - name: env
    type: string

variables:
- group: testVars

jobs:
- deployment: 
  environment: ${{ parameters.env }}
  strategy:
    runOnce:
      deploy:
        steps:
        - script: |
            echo "The password is $(password)" 